### ISSUE TITLE
TaskJMRun.groovy has a case issue for jmGlobalProperties...

### ISSUE THREAD

**Issue by jjou1** [jmeter-gradle-plugin/jmeter-gradle-plugin#106]
Issue:  
           //jmGlobalProperties
            if (project.jmeter.jmG**L**obalProperties != null) {
                project.jmeter.jmG**l**obalProperties.each { property -> args.add("-G" + property) }
            }

The letter should lower case "l" not upper case "L". This property code is broken and needs to be fixed asap...

**Comment by ghost** [comment]
Fixed with #105

**Comment by ghost** [comment]
Can you run an older version of the plugin for the time being?

1.0.8-3.3 (might have issues see issue #104)
1.0.7-3.0-BETA

Alternatively, what happens if you create an empty list in the jmeter config called jmGLobalProperties?
