### ISSUE TITLE
Adding Topics to your repository

### ISSUE THREAD

**Issue by pmouawad** [jmeter-gradle-plugin/jmeter-gradle-plugin#108]
Hello,
You should add topics to your repository to improve its discoverability:

- https://github.com/blog/2309-introducing-topics

I would suggest:
- build
- jmeter
- gradle
- continuous-integration
- performance
- load-test
- performance-analysis

Regards
Philippe M.
@philmdot

**Comment by foragerr** [comment]
Great suggestion, added. Thank you.
