### ISSUE TITLE
Version 1.0.10-3.3 fails looking for log4j log.

### ISSUE THREAD

**Issue by g1ps** [jmeter-gradle-plugin/jmeter-gradle-plugin#109]
Version 1.0.10-3.3 fails for us with
```
<test path>:jmRunERROR StatusLogger Unable to access file:/C:/QA/workspace/%20Performance%20Tests/Client/tests/RestAPI_StaticGetGroup/build/jmeter/bin/log4j2.xml
java.io.FileNotFoundException: C:\QA\workspace\Performance Tests\Client\tests\RestAPI_StaticGetGroup\build\jmeter\bin\log4j2.xml (The system cannot find the path specified)
```
We were previously running 1.0.8-3.0-SNAPSHOT which didn't do this. `\build\jmeter\bin\` does not exist.

**Comment by g1ps** [comment]
Any help with this?

**Comment by birajendunetskope** [comment]
is this specific to platform. My colleague is facing this in his Windows system. I don't see this issue in my mac system.

**Comment by hoos** [comment]
Copying the log4j file in place under `.../build/jmeter/bin` resolves the issue on Windows 10, but I assume this isn't expected behavior.

**Comment by g1ps** [comment]
Thanks, guys. It's good to know it's not just me. @birajendunetskope, I don't know. I'm only running on Windows at present. @hoos, that's good to know, thanks, but not a practical solution for us, I don't think. I will experiment when I get a chance. Hopefully we'll get a fix soon.

**Comment by g1ps** [comment]
Any update here?

**Comment by loverde** [comment]
FWIW, you can work around this by putting a log4j2.xml somewhere in your project and adding a gradle task to copy it to the location giving the error.  E.g.

```
task copyToBin(type: Copy) {
    into "$buildDir/jmeter/bin"
    from "$projectDir/src/main/resources"
    include "log4j2.xml"
}

jmRun.dependsOn copyToBin
jmGui.dependsOn copyToBin
```

**Comment by birajendunetskope** [comment]
Yes I have fixed the above way

**Comment by g1ps** [comment]
Thanks, @loverde. I have _finally_ managed to get to this and it's working for now. A proper fix would be nice, though. It looks like this project is adrift.  :anguished:

**Comment by g1ps** [comment]
I'm leaving this one open so an explanation can be provided as this shouldn't have happened and the work-around should only be temporary.

Thanks.

**Comment by foragerr** [comment]
The explanation is pretty straightforward, JMeter added the log4j2.xml file somewhere between versions 3.0 and 3.3. When I merged the PR that upgraded this plugin from 3.0 -> 3.3, we clearly didn't test enough to catch that.

The file will have to be packaged with the plugin so it can be dropped into the right place at runtime. I'll find time to check-in a fix. Contributions are always welcome :)

**Comment by foragerr** [comment]
This is now fixed in dev build `1.1.1-4.0-SNAPSHOT` if you'd like to give it a shot.

[Using dev builds](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/wiki/Dev-Builds)

**Comment by slPerryRhodan** [comment]
Would be nice if this will be fixed or is this plugin dead?

**Comment by g1ps** [comment]
> Would be nice if this will be fixed or is this plugin dead?

I believe it's been working for me using the version suggested above for the last couple of years. @foragerr has not had time to improve it for some time but at least it's working. I haven't checked whether there are any active forks, either.
