### ISSUE TITLE
Extended reports filenames should contain timestamps

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#11]
Quoting from [here](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/10):

> 1. The timestamp did not appear on any of the .png or .csv output files either.
> 2. The project '.jmx' file extension did not appear in the names either.

**Comment by djangofan** [comment]
To be clear:
1. I would expect that when `jmeter.save.saveservice.timestamp_format=none` is set, then all the .png and .csv output files should not have names that include either the timestamp or the .jmx extension.
2. When the above property is NOT set, then the timestamp should show up on all filenames, including the report.html file.

**Comment by foragerr** [comment]
Closed in 0.5.0

**Comment by djangofan** [comment]
@foragerr   Shouldn't this bug be re-opened?   If I set  jmeter.save.saveservice.timestamp_format=none , then I am expecting all the test artifacts generated in the results folder to NOT have a timestamp in their file names.

**Comment by foragerr** [comment]
no, that'll get fixed when #10 and #12 are closed.
