### ISSUE TITLE
The src/test/jmeter/jmeter.properties and user.properties not being merged into an effective properties file

### ISSUE THREAD

**Issue by djangofan** [jmeter-gradle-plugin/jmeter-gradle-plugin#12]
I just tried v0.1.6. Didn't notice this until now, but whenever I set `jmeter.save.saveservice.timestamp_format=none` in the `src/test/jmeter/jmeter.properties` file, when Gradle runs the build, it is failing to generate a 'interpolated' (that means a shortened file without comments) `jmeter.properties` file in the location `build/jmeter/jmeter.properties` . Instead , what it does is copy/overwrite a new 'default' jmeter.properties file. Therefore, when it runs, I am now unable to set that property to 'none'. Even when I remove the 'clean' phase from my Gradle build, same thing. Can you verify? It's easy to reproduce with my project at: https://github.com/djangofan/launch-jmeter

Also, I am now noticing that the `src/test/jmeter/user.properties` file does not get copied into place in the `build/jmeter/user.properties` as it probably should .

**Comment by djangofan** [comment]
What the Gradle plugin should 'probably do' is get the properties from `jmeter.properties` and the properties passed to the Gradle task and merge them into an build/jmeter/jmeter.properties file that contains no comments;  the resulting file is just a merge of all passed properties for this particular run of the build.  I'm guessing that property values passed to the Gradle task should override any props that were set in jmeter.properties.   (not to be confused with or mixed with user.properties file)

I say this because (the above) is the actual behavior of the Maven jmeter plugin.

**Comment by foragerr** [comment]
Hey @djangofan I'm trying to understand this and #10 so I can fix them, I'm a little confused:

There are two properties files, `jmeter.properties` and then there is `user.properties`. Which one are you putting your custom properties in? In jmeter general usage guidelines, all custom settings go into user.properties

The way properties are picked up is: 
- default jmeter.properties (or the file from `jmPropertyFile`) is loaded
- user properties defined in `jmUserPropertiesFiles` is loaded and any entries here override same entry from jmeter.properties

A coalesced property file is not written to disk.

Is this different from what you're observing?

**Comment by djangofan** [comment]
@foragerr  Actually, you are right.  They are not combined.  I thought I observed that behavior in the Maven plugin but what actually happens is that the Maven plugin copies the entries from user.properties and jmeter.properties into  files of the same name in the 'target/jmeter/bin/'  folder but strips out all the comments from the files.  Then, Jmeter runs and picks up those versions of the files.    Just something I noticed.  Not sure if you want this Gradle plugin to behave the same?

**Comment by foragerr** [comment]
I'm not sure I see value in writing out an effective properties file to disk for a plugin user. It maybe useful for debugging but not much else.

Can I close this defect?

**Comment by djangofan** [comment]
Yes IF the user.properties also gets copied into place, which I am not sure
I saw...

**Comment by djangofan** [comment]
As I said in my original bug description, also make sure it's NOT the default version of jmeter.properties being copied into place, which is what I think I was seeing .   That may have been the cause of my timestamp options being ignored on the build...

**Comment by DKroot** [comment]
My custom settings in `src/test/jmeter/jmeter.properties` seem to take effect fine. I moved them all from `user.properties` to `jmeter.properties` since the plug-in seems to require the presence of `src/test/jmeter/jmeter.properties` (Issue #31)
