### ISSUE TITLE
Apache mongodb not loaded in plugin

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#13]
```
2015/07/17 16:49:11 ERROR - jmeter.JMeter: Error in NonGUIDriver java.lang.IllegalArgumentException: Problem loading XML from:'D:\GAP_repository\planning-service\receipt-service\src\test\Load&ReviewReceipts.jmx', conversion error com.thoughtworks.xstream.converters.ConversionException: org.apache.jmeter.protocol.mongodb.config.MongoSourceElement : org.apache.jmeter.protocol.mongodb.config.MongoSourceElement
---- Debugging information ----
message : org.apache.jmeter.protocol.mongodb.config.MongoSourceElement
cause-exception : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message : org.apache.jmeter.protocol.mongodb.config.MongoSourceElement
class : org.apache.jorphan.collections.ListedHashTree
required-type : org.apache.jorphan.collections.ListedHashTree
converter-type : org.apache.jmeter.save.converters.HashTreeConverter
path : /jmeterTestPlan/hashTree/hashTree/MongoSourceElement
```

**Comment by foragerr** [comment]
@cfalba80 Would it be possible to upload a simple gradle project to github to reproduce this issue?

**Comment by cfalba80** [comment]
Hello,

this is the url of the project: https://github.com/cfalba80/TestJmeter

Thanks.

**Comment by cfalba80** [comment]
Hello foragerr,
so this is a bug in the plugin? do you have an estimate on when it can be resolved?
Thanks for your help.

**Comment by foragerr** [comment]
If mongo protocol jars are indeed missing from jmeter process classpath, then it is a plugin defect. If it is external jars, then it isn't really a plugin problem, but likely a configuration issue.

I haven't had a chance to look at it yet, I assigned it to myself just now :)
I'll take a look at it tonight and give an estimate.

**Comment by cfalba80** [comment]
Hello,

according to jmeter versin 2.13 the apache mongodb plugin is included there, but it doesn't get loaded when launching the jmeter task.

Thanks

**Comment by foragerr** [comment]
This was indeed an issue with the plugin classpath generation. It is fixed in 0.5.2

The usage for this plugin is slightly different from the other plugin, your build.gradle should look like this:

```
apply plugin: 'net.foragerr.jmeter'

buildscript {
    repositories { 
        mavenCentral()
        maven {url 'https://dl.bintray.com/jmeter-gradle-plugin/jmeter'}
    }
    dependencies {
        classpath "net.foragerr.jmeter:jmeter-gradle-plugin:0.5.2-2.13"
    }
}
jmeter {
    jmTestFiles = [file("src/test/Load&ReviewReceipts.jmx")]
    jmPropertyFile = file("src/test/jmeter.properties")
}
```

The gradle task to run jmeter test is `gradle jmRun`

**Comment by cfalba80** [comment]
Hello foragger,

thanks for your help, i have another question, when running "gradle jmReport" i am getting this error now:
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method org.apache.tools.ant.DirectoryScanner#setBasedir.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.io.File]
        [class java.lang.String]
        at net.foragerr.jmeter.gradle.plugins.utils.JMUtils.scanDir(JMUtils.groovy:33)
        at net.foragerr.jmeter.gradle.plugins.utils.JMUtils$scanDir.call(Unknown Source)
        at net.foragerr.jmeter.gradle.plugins.TaskJMReports.jmCreateReport(TaskJMReports.groovy:44)

this is my build.gradle:
apply plugin: 'net.foragerr.jmeter'

buildscript {
    repositories { 
        mavenCentral()
        maven {url 'https://dl.bintray.com/jmeter-gradle-plugin/jmeter'}
    }
    dependencies {
        classpath "net.foragerr.jmeter:jmeter-gradle-plugin:0.5.2-2.13"
    }
}
jmeter {
    jmTestFiles = [file("src/test/Load&ReviewReceipts.jmx")]
    jmPropertyFile = file("src/test/jmeter.properties")
    enableReports = true

}

maybe it is a config issue?

Thank you.

**Comment by foragerr** [comment]
hmm, that's weird. If it isn't too much trouble, could you please raise this as a new issue? Thanks!

**Comment by cfalba80** [comment]
Hello,

is done, issue # 17

thanks.
