### ISSUE TITLE
Please verify that Jmeter HTTP Recorder plugin works in latest release

### ISSUE THREAD

**Issue by djangofan** [jmeter-gradle-plugin/jmeter-gradle-plugin#14]
Please verify that Jmeter HTTP Recorder plugin works in latest release.   I had some trouble getting that plugin to work , which I suspect might be a by-product of using gradlew.bat  or something.  Not sure what is wrong but I am entering this bug just so that we remember to make sure that in the next release of the jmeter-gradle-plugin, that the "HTTP (S) Test Script Recorder" plugin still works when Jmeter is launched in GUI mode.   ( see http://jmeter.apache.org/usermanual/jmeter_proxy_step_by_step.pdf  for more info)

**Comment by foragerr** [comment]
I got an error that jmeter could not find keytool.exe. Is this the same error you're seeing?

**Comment by djangofan** [comment]
Yes.  That is exactly it.  I spent some time on it and haven't figured it
out yet.  Let me know if you know what the problem is.  I tried a bunch of
things already....

**Comment by foragerr** [comment]
keytool is a certificate generation tool distributed with JRE/JDK, not with jmeter. Regular jmeter apparently finds it somehow in the JRE/JDK's /bin folder. We need to somehow ensure that the jmeter instance we launch with the plugin knows where to look for keytool. Right now it is looking in `$project.buildDir/jmeter/bin` where it obviously does not find keytool.

**Comment by djangofan** [comment]
Found a similar issue: http://stackoverflow.com/questions/30411520/how-to-overcome-the-filename-or-extension-is-too-long-error-with-gradle-in-win

**Comment by djangofan** [comment]
Still not working in 0.5.6 version of plugin.

**Comment by foragerr** [comment]
Fixed in 1.0.2-SNAPSHOT.
will be released in 1.0.2

**Comment by djangofan** [comment]
I just tried 1.0.2-2.13-SNAPSHOT.  I built it locally and pushed it to my local Maven repo.  Then I ran the  'jmeter-gradle-plugin-adv-example' project.   Jmeter starts up just fine.   I pushed my change to the build.gradle to that project.     

THE PROBLEM:   There still remains 2 noticeable problems:  
1.  None of the extended Jmeter plugin packs are loading properly.
2.  There is an absence of the  HTTP Recorder plugin.

Just let me know if you cannot reproduce.  It seems to be a valid issue from my point of view.   If you need me to analyze further and figure out exactly what I think the problem is, then I can do that, just let me know.

**Comment by foragerr** [comment]
Maybe I misunderstood your original reported issue - What is the HTTP recorder plugin? Can you link me to this feature?

What I fixed is the out of box HTTP recording, which didn't work earlier, because JMeter couldn't find keytool.exe, and now it does after this change.

**Comment by djangofan** [comment]
Yes, your right.  The "out of the box Http recorder" in the Workbench works fine.   I guess the only problem is that all the 3rd party plugin packs are not getting loaded.  What I mean by this is all the plugin packs from this location:  http://jmeter-plugins.org/   .  You can verify this because, for example, when you browser through the Thread Group menus to add controllers,  you will not see any of the controllers that are part of the plugin packs.  One example is "HTTP Raw Request" from the "Extras Set"

**Comment by foragerr** [comment]
This should now be resolved, I just fixed #13 and #38

**Comment by djangofan** [comment]
Yes @foragerr ,  it is now fixed.   Very good work.  Thanks. :-)
