### ISSUE TITLE
Plugin 0.5.0 throws GradleException instead of allowing Jmeter to reveal exceptions

### ISSUE THREAD

**Issue by djangofan** [jmeter-gradle-plugin/jmeter-gradle-plugin#15]
Plugin 0.5.0 throws GradleException instead of allowing Jmeter to reveal its errors.   Maybe I am misunderstanding the intent, or I could be wrong, but I view this as a problem since:
- When there are test errors, we want Jmeter to continue to generate a report, instead of Gradle bailing out of the build and showing a ErrorScanner exception that hides the actual error.
-  It shouldn't be the job of the jmeter-gradle-plugin to scan for errors and report on them.  That is the domain of the jMeter HTML report output.

```
    protected boolean lineContainsForErrors(String line) {
        if (line.contains(PAT_ERROR)) {
            if (this.ignoreErrors) {
                return true
            } else {
                throw new GradleException("There were test errors.  See the jmeter logs for details.")
            }
        }
        if (line.contains(PAT_FAILURE) || line.contains(PAT_FAILURE_REQUEST)) {
            if (this.ignoreFailures) {
                return true
            } else {
                throw new GradleException("There were test failures.  See the jmeter logs for details.")
            }
        }
        return false
    }
```

**Comment by foragerr** [comment]
You can set `ignoreErrors` and `ignoreFailures` to false to get the behavior you want. I believe they're both false by default.

The error scanner feature exists so you can mark CI builds (Jenkins for example) as failed if there is a jmeter error.

**Comment by djangofan** [comment]
I'm not quite understanding.  On your two points:
- I can see that you are using ignoreErrors=false and ignoreFailures=false in order to "fast fail" the suite.   The problem with that is when you do that, I think it won't generate a HTML report, which IMHO is undesired behavior.  HTML report is useful for examining suite errors and even for HTTP failures.
-  I can see that you are using the ErrorScanner as a way to force the exit code to 0  and get a RED dot in Jenkins rather than a YELLOW unstable mark.  Personally I feel that allowing a test suite with a few errors show as unstable is desirable behavior that is easily over-ridden using the Jenkins Groovy Post-build plugin, which could enable you to force RED on a error threshold of 1, 2, or whatever amount of errors.  That being the case, not having the feature certainly isn't a blocker.    Also, we know that "HTTP test failures" exit Jmeter in-error and show a RED, with exit code 0 anyways, and so I don't see the reason why you would ever want to set ignoreFailures=true  since Jenkins will result in a RED ball even if you don't set it to true.   The Maven jmeter plugin only has a ignoreErrors option and doesn't have a ignoreFailures (probably for the reason I said above).   Perhaps it could be useful for a non-Jenkins CI server?

Just some thoughts.  Correct me if I am wrong, and let's hash this out. :-)  I can be convinced otherwise I think.

**Comment by foragerr** [comment]
There's a typo in my earlier comment :disappointed: Makes it confusing.

I think `ignoreFailures=true` and  `ignoreErrors=true` should be the default setting so they don't halt a gradle build. I will make this change. 

If someone wants to make the gradle build fail based on errors or test failures, it is available as an option. The reports not being generated is a bit of a problem - lets make a note about this in documentation.

You can still run `gradle jmReport` after a test fails to generate reports from jmx files - I haven't tested this scenario though, not sure how report generation code behaves if there are failures in the results.

**Comment by djangofan** [comment]
Ok, if you make your change to the default configuration today, then tonight I can try it out and verify it using the https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin-adv-example project, as I tried to do last night.

**Comment by foragerr** [comment]
Changed already, in v0.5.1

**Comment by djangofan** [comment]
Just to correct an earlier statment I made.  In the Maven-jmeter plugin, the default behavior is for the jmeter build to show a Green/Blue ball when just a few of the tests have errors.   So, if you wanted to force a YELLOW unstable ball, and if the plugin doesn't handle that, then you would have to use the Gradle post-build plugin to adjust the ball color by reading the .xml unit test result file.
