### ISSUE TITLE
Can´t execute jmRun due to "java.io.IOException: CreateProcess error=206, The filename or extension is too long"

### ISSUE THREAD

**Issue by cfalba80** [jmeter-gradle-plugin/jmeter-gradle-plugin#18]
I have another issue, need to integrate this plugin in an existing gradle project wich has another classpath dependency configured, when i add the classpath for this plugin i am getting this error when trying to run jmRun:

```
Caused by: java.io.IOException: Cannot run program "java" (in directory "D:\workspace_gap\TestJmeter\build\jmeter"): CreateProcess error=206, The filename or extension is too long
at java_lang_ProcessBuilder$start$2.call(Unknown Source)
at net.foragerr.jmeter.gradle.plugins.worker.JMeterRunner.launchProcess(JMeterRunner.groovy:16)
at net.foragerr.jmeter.gradle.plugins.worker.JMeterRunner.executeJmeterCommand(JMeterRunner.groovy:25)
at net.foragerr.jmeter.gradle.plugins.worker.JMeterRunner$executeJmeterCommand.call(Unknown Source)
at net.foragerr.jmeter.gradle.plugins.TaskJMRun.executeJmeterTest(TaskJMRun.groovy:104)
... 57 more
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
... 62 more
```

The classpath overflows when trying to add this and the java process fails.
This is the build.gradle:
    apply plugin: 'net.foragerr.jmeter'

```
buildscript {
    repositories { 
        mavenCentral()
        maven {url 'https://dl.bintray.com/jmeter-gradle-plugin/jmeter'}
        maven { url 'http://artifactory.gapinc.dev/artifactory/remote-repos' }
        ivy {
            layout 'maven'
            url 'http://artifactory.gapinc.dev/artifactory/remote-repos'
        }
    }
    dependencies {
        classpath 'com.gap:gap-gradle-plugin:+'
        classpath "net.foragerr.jmeter:jmeter-gradle-plugin:0.5.4-2.13"
    }

}

jmeter {
    jmTestFiles = [file("src/test/Load&ReviewReceipts.jmx")]
    jmPropertyFile = file("src/test/jmeter.properties")
    enableReports = false
    enableExtendedReports = true
}
```

**Comment by foragerr** [comment]
sounds familiar, I think this was reported on the old plugin before. 

found it: https://github.com/kulya/jmeter-gradle-plugin/issues/49

**Comment by cfalba80** [comment]
yes it is similar to that one, using windows too.

**Comment by djangofan** [comment]
Yes, using v0.5.4 the https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin-adv-example  project, I am able to reproduce this issue.   Seems a little similar to that other issue #14 where the keytool  could not be found.

**Comment by foragerr** [comment]
@djangofan did you always have this issue with the adv-example? I thought it worked fine earlier?

This issue is a bit of a thinker. The way it is currently implemented, the entire gradle classpath is applied to the jmeter process. This classpath can be quite long, gradle cache having random strings of numbers (SHA Hashes I think) in folder names doesn't help! If you keep adding dependencies to gradle classpath, eventually the windows path size limit is reached.

Now to get around this, maybe we can filter the classpath to only keep what jmeter absolutely needs. this can get tricky, and may not solve the problem at all if the added dependencies are _for_ jmeter

I likely wont be turning this around very quickly.

**Comment by foragerr** [comment]
Apparently another way to do this is to create a temporary manifest only Jar instead of passing classpath on commandline.

Ref:https://github.com/gatling/gatling/issues/2732  
Ref: http://stackoverflow.com/questions/201816/how-to-set-a-long-java-classpath-in-windows

**Comment by foragerr** [comment]
Implemented the temp jar method.  
please retest with v0.5.5

**Comment by cfalba80** [comment]
It is working now, thanks

**Comment by djangofan** [comment]
Yes, verified working.
