### ISSUE TITLE
PR #21 broke jmreport which also uses JMUtils.ScanDir()

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#23]
> No signature of method: static net.foragerr.jmeter.gradle.plugins.utils.JMUtils.scanDir() is applicable for argument types: (org.gradle.api.internal.project.DefaultProject_Decorated, java.lang.String, java.io.File) values: [root project 'jmeter-gradle-plugin-test1', *_/_.xml, D:\Dev\github\jmeter-gradle-plugin-test1\build\jmeter-report] Possible solutions: scanDir(org.gradle.api.Project, [Ljava.lang.String;, [Ljava.lang.String;, java.io.File)

**Comment by foragerr** [comment]
which is why we badly need some unit tests :(

**Comment by djangofan** [comment]
If the jmReport does not handle multiple project file outputs, then you will be hearing from me soon about fixing that.   At some point, when things slow down a little, I will start helping.
