### ISSUE TITLE
assertionResult's in extended report

### ISSUE THREAD

**Issue by pbellchambers** [jmeter-gradle-plugin/jmeter-gradle-plugin#30]
Is it possible to display assertionResult's in the extended html report? As far as I can tell it just displays performance statistics without even showing if any errors occurred.

Is this a missing feature or am I missing some setting?

**Comment by foragerr** [comment]
That isn't an available feature right now, but sounds like a nice thing to have. 
We're currently using [jmeter-plugins](http://jmeter-plugins.org/wiki/JMeterPluginsCMD/) to generate graphs and CSVs, wonder if there is a flag there to include assertionResults directly.

**Comment by djangofan** [comment]
In theory this should be possible.  It would require enabling this flag on your Jmeter test run:
    jmeter.save.saveservice.assertion_results_failure_message=true
Then, in theory, the test result HTML report could pull those values.   This would require that you first do a test run and make sure your assertions are getting stored in the results XML output file.

**Comment by foragerr** [comment]
combined with @djangofan's comment above, and a custom XSLT, it is possible to pull assertion results into the HTML report. see #34
