### ISSUE TITLE
All tasks fail with a runtime error in the absence of custom jmeter.properties

### ISSUE THREAD

**Issue by DKroot** [jmeter-gradle-plugin/jmeter-gradle-plugin#31]
I have a JMeter test plan that works fine in a native JMeter. I'm trying to integrate it with our build in Gradle.

My custom JMeter properties are in `src/test/jmeter/user.properties`. There is no `src/test/jmeter/jmeter.properties`. This works fine with JMeter, but the plug-in 0.6.2-2.13 blows up with

```
Execution failed for task ':jmRun'.
> No signature of method: java.io.File.plus() is applicable for argument types: (java.lang.String) values: [/jmeter-plug
in.properties]
Possible solutions: list(), list(java.io.FilenameFilter), is(java.lang.Object), use([Ljava.lang.Object;), split(groovy.l
ang.Closure), wait()
```

**Comment by foragerr** [comment]
@DKroot would it be possible to post a stripped down gradle project that reproduces this issue?

**Comment by foragerr** [comment]
Does the plugin work if you create an empty `src/test/jmeter/jmeter.properties` file?

**Comment by DKroot** [comment]
Yes, it does work with an empty `src/test/jmeter/jmeter.properties`. That's how I had solved this problem originally before I decided simply to move everything from user.properties to jmeter.properties.

I can probably extract stripped down project to reproduce the issue if you need it.

**Comment by foragerr** [comment]
The plugin is supposed to use a default `jmeter.properties` if one isn't supplied. Can't figure out what's happening in your case, a stripped down project would be very helpful.

**Comment by DKroot** [comment]
I have extracted the stripped down demo and packed into a .ZIP. Where do you want me to post it?

**Comment by foragerr** [comment]
You can either post it as a github repo, or email me at foragerr@gmail.com

**Comment by DKroot** [comment]
Sent via email

**Comment by foragerr** [comment]
Fixed in dev build 1.0.2-2.13-SNAPSHOT will be released in 1.0.2

**Comment by foragerr** [comment]
Note to self: Another simple error in untested code path - should really be caught by unit tests.

Thanks for the bug report @DKroot

**Comment by rinoto** [comment]
Fyi: the README.md still points to the version with this problem: 1.0-2.13.

Using 1.0.3-2.13 works fine.

**Comment by foragerr** [comment]
@rinoto Thank you for making the wiki edit!
