### ISSUE TITLE
Support optional URL field in the reports

### ISSUE THREAD

**Issue by DKroot** [jmeter-gradle-plugin/jmeter-gradle-plugin#34]
I like plugin reports produced by `jmReport`. We're planning to use and publish the basic (non-extended) reports on our Jenkins CI server, and it'll mostly fit our needs with one notable exception.

We customized saveservice properties to include the URL field (`jmeter.save.saveservice.url=true`).  The rest are all default fields. URLs are critical for us for several reasons, primarily because we test RESTful services and average metrics for the same JMeter label between different test inputs, which result in different URLs. I'm pretty sure that other people often use URL field in JMeter reports.

Would it be possible to include URLs in the basic plugin report if they are present in JMeter XML?

**Comment by foragerr** [comment]
@DKroot the basic report is produced by transforming jmeter xml  into html using an XSLT. Would it suffice if the plugin allowed you to provide your own custom `.xsl` file instead of using the predefined one? That will allow you to add any custom field you want.

**Comment by DKroot** [comment]
Yes, I could live with that. And yes, it would be useful functionality for people to include additional or custom fields. The minus is that people would copy the default plugin XSLT and customize, but then we would have to maintain it going forward because plugin's XSLT might be enhanced and diverge with time.

The other option is to support URL in the default XSLT if URL is present. I think that it would be valuable for many people.

**Comment by foragerr** [comment]
The default XSLT is designed around default saveservice values. I feel that if we check for 1 changed saveservice value explicitly, we should really check for them all - which is a pain :)

~~I'm using the more basic of two xsl files that ships with jmeter in the extras folder. The other one has "detail" in its filename. Wonder if that one does URLs, if yes, the plugin should probably provide a choice between the two, besides allowing for further customization.~~

~~Will take a look at the second XSLT.~~

Step1: allow custom XSLT, so I can use that to test the other `.xsl` file.

**Comment by DKroot** [comment]
I generally see your point. It's just if I can support URLs in the report, we can put plugin's use in production. This is the last gap for me. My other issues are nice to have kind of things.

**Comment by foragerr** [comment]
Apparently I am already using the "detail" .xsl file. I'll push the feature to use custom XSLT for now.
If you want to contribute a modified XSLT, I'll consider including it with the plugin.

**Comment by foragerr** [comment]
To use custom XSLT: 

```
jmeter{
    reportXslt = "src/test/jmeter/jmeter-results-report_21.xsl"
}
```
