### ISSUE TITLE
Plugin could provide statistical table reports for all queries in a test suite

### ISSUE THREAD

**Issue by djangofan** [jmeter-gradle-plugin/jmeter-gradle-plugin#35]
The jmeter-analysis-maven-plugin provides statistical table HTML analysis reports to test results.   It seems like this plugin should also be able to generate those artifacts.  See attachment to this request for an example.

![jmeterreport](https://cloud.githubusercontent.com/assets/810894/10830513/38b95b42-7e3d-11e5-8069-b82733d97e48.png)

**Comment by foragerr** [comment]
I started a different project to mimic the jmeter-analysis-plugin [here](https://github.com/jmeter-gradle-plugin/jmeter-analysis-gradle-plugin). Needless to say I haven't made any progress yet :)

Not sure if there is value in replicating those features here.
