### ISSUE TITLE
Add support for passing JVM system properties to JMeter

### ISSUE THREAD

**Issue by lourish** [jmeter-gradle-plugin/jmeter-gradle-plugin#37]
It's not possible to pass '-D' parameters to the JMeter process. This is required for many things, but one JMeter-specific use is when accessing a Java keystore: http://jmeter.apache.org/usermanual/component_reference.html#Keystore_Configuration

So, for passing system properties it would be useful to be able to do something like:

```
jmeter {
    systemProperties.putAll System.properties
    systemProperties.put('javax.net.ssl.keyStore', './keystore')
    systemProperties.put('javax.net.ssl.keyStorePassword', 'password')
}
```

or even

```
jmeter {
    jvmOptions = ['-XX:ErrorFile=./hs_err_pid%p.log',
         '-XX:+UseG1GC',
         '-Djavax.net.ssl.keyStore=./keystore',
         '-Djavax.net.ssl.keyStorePassword=password']
}
```

**Comment by foragerr** [comment]
We've inherited code from the other plugin, but not issues - which we probably should as well.. So, thanks for bringing this up.

So there are two ways to implement this. 
1. Use a keyword in the jmeter{} section to define system properties, like you've described
2. Blindly pick up all -D arguments from the parent gradle process

Could be a combination of the two as well, pick up gradle -D but allow overriding through jmeter {} configuration elements.

Preferences?

**Comment by lourish** [comment]
The second option, picking up -D's from the gradle process, is problematic e.g. for the keystore example replacing the java keystore for gradle just to pass properties to JMeter could mean that gradle's ability to retrieve dependencies over https blows up.

So I think the first option, allowing the author to set the properties they need, is better. It's also what the Java plugin's tasks do so it would be consistent.

**Comment by djangofan** [comment]
Yes, allowing a override via the gradle 'jmeter' plugin task sounds like
the right idea.   If someone wanted Gradle to read a property from Gradle's
parent JVM (ex: '-D' args), which is probably a common thing (ex: when ran
from Jenkins), then they could write build script code to do that.

**Comment by foragerr** [comment]
Added two new configurable elements:

```
jmeter{
  //List of files
  //Passed to jmeter process as -S option
  jmSystemPropertiesFiles = ['/path/to/system.properties']

  //List of strings of form 'key=value'
  //Passed to jmeter process as -D option. 
  //note: the plugin prepends -D to the key string, so cannot use options like '-XX'
  //adding -XX option is throwing an error that I need to look into.
  jmSystemProperties = ['key1=value1', 'javax.net.ssl.keyStore=./keystore']
}
```

Order of precedence:
1. Internally hard coded plugin values are applied first
2. properties from system.properties files declared in jmSystemPropertiesFiles are applied, and will override values from `#1` caution: it is possible to break the plugin by overriding something like classpath
3. properties from jmSystemProperties are applied, and will override values from `#2` and `#1`

I checked in this change, but haven't released yet. Need to run some tests and fix the -XX error. Feel free to try out the dev build here: 

```
repositories {
    maven {url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'}
}
dependencies {
    classpath "net.foragerr.jmeter:jmeter-gradle-plugin:+"
}
```

**Comment by lourish** [comment]
That's great, I used jmSystemProperties and it does just what I need it to, thanks!

**Comment by foragerr** [comment]
Fixed in dev build 1.0.1-2.13-SNAPSHOT. Will be released in 1.0.1-2.13

Changes since the usage comment above:
Added support for options of the type '-XX' which do not have a leading -D, Consequently `-D` is not appended automatically and needs to be part of supplied arguments when required. Usage example:

```
jmSystemProperties = ['-Dkey1=value1', '-Djavax.net.ssl.keyStore=./keystore', '-XX:+UseG1GC']
```

**Comment by jmattheis** [comment]
@foragerr This usage example should also be in the wiki, I needed now to search the changelog to know how to use the `jmSystemProperties`

**Comment by foragerr** [comment]
@jmattheis Added snippet to wiki: https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/wiki/Advanced-Usage

Wiki edits are public btw, feel free to make additions!
