### ISSUE TITLE
It is impossible to use jp@gc JSONPathExtractor in jmx project.

### ISSUE THREAD

**Issue by kibmitek** [jmeter-gradle-plugin/jmeter-gradle-plugin#38]
In my jmx project I use jp@gc JSONPathExtractor and jp@gc JSONPathAssertion and get an error(stacktrace below).
The same situation a catched with com.github.kulya:jmeter-gradle-plugin:1.3.1-2.6.
And I found workaround(but I dont like it) for both plugins:
1. put jars json-path-0.9.0.jar and json-smart-1.2.jar into \build\jmeter\lib folder
2. put jars JMeterPlugins-Extras.jar and JMeterPlugins-ExtrasLibs.jar into \build\jmeter\lib\ext
It will be nice to use plugin as is from the box without adding this jars.

Stacktrace:

D:\jmeter_gradle_foragger>gradle jmRun jmReport
:jmInit

> Building 33% > :jmRunError in NonGUIDriver java.lang.IllegalArgumentException: Problem loading XML from:'D:\api_tes
> ts_gradle_foragerr\src\test\jmeter\api_tests.jmx', conversion error com.thoughtworks.xstream.converters.ConversionExc
> eption: com.atlantbh.jmeter.plugins.jsonutils.jsonpathextractor.JSONPathExtractor : com.atlantbh.jmeter.plugins.jsonutils.js
> onpathextractor.JSONPathExtractor
> ---- Debugging information ----
> message             : com.atlantbh.jmeter.plugins.jsonutils.jsonpathextractor.JSONPathExtractor
> cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
> cause-message       : com.atlantbh.jmeter.plugins.jsonutils.jsonpathextractor.JSONPathExtractor
> class               : org.apache.jorphan.collections.ListedHashTree
> required-type       : org.apache.jorphan.collections.ListedHashTree
> converter-type      : org.apache.jmeter.save.converters.HashTreeConverter
> path                : /jmeterTestPlan/hashTree/hashTree/hashTree/hashTree[5]/com.atlantbh.jmeter.plugins.jsonutils.jsonpathe
> xtractor.JSONPathExtractor
> line number         : 101
> ------------------------------- : com.atlantbh.jmeter.plugins.jsonutils.jsonpathextractor.JSONPathExtractor : com.atlantbh.j
> meter.plugins.jsonutils.jsonpathextractor.JSONPathExtractor
> ---- Debugging information ----
> message             : com.atlantbh.jmeter.plugins.jsonutils.jsonpathextractor.JSONPathExtractor
> cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
> cause-message       : com.atlantbh.jmeter.plugins.jsonutils.jsonpathextractor.JSONPathExtractor
> class               : org.apache.jorphan.collections.ListedHashTree
> required-type       : org.apache.jorphan.collections.ListedHashTree
> converter-type      : org.apache.jmeter.save.converters.HashTreeConverter
> path                : /jmeterTestPlan/hashTree/hashTree/hashTree/hashTree[5]/com.atlantbh.jmeter.plugins.jsonutils.jsonpathe
> xtractor.JSONPathExtractor
> ## line number         : 101
> 
> message             : com.atlantbh.jmeter.plugins.jsonutils.jsonpathextractor.JSONPathExtractor : com.atlantbh.jmeter.plugin
> s.jsonutils.jsonpathextractor.JSONPathExtractor
> ---- Debugging information ----
> message             : com.atlantbh.jmeter.plugins.jsonutils.jsonpathextractor.JSONPathExtractor
> cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
> cause-message       : com.atlantbh.jmeter.plugins.jsonutils.jsonpathextractor.JSONPathExtractor
> class               : org.apache.jorphan.collections.ListedHashTree
> required-type       : org.apache.jorphan.collections.ListedHashTree
> converter-type      : org.apache.jmeter.save.converters.HashTreeConverter
> path                : /jmeterTestPlan/hashTree/hashTree/hashTree/hashTree[5]/com.atlantbh.jmeter.plugins.jsonutils.jsonpathe
> xtractor.JSONPathExtractor
> ## line number         : 101
> 
> cause-exception     : com.thoughtworks.xstream.converters.ConversionException
> cause-message       : com.atlantbh.jmeter.plugins.jsonutils.jsonpathextractor.JSONPathExtractor : com.atlantbh.jmeter.plugin
> s.jsonutils.jsonpathextractor.JSONPathExtractor
> first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:67)
> class               : org.apache.jmeter.save.ScriptWrapper
> required-type       : org.apache.jorphan.collections.ListedHashTree
> converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
> path                : /jmeterTestPlan/hashTree/hashTree/hashTree/hashTree[5]/com.atlantbh.jmeter.plugins.jsonutils.jsonpathe
> xtractor.JSONPathExtractor
> line number         : 101
> ## version             : 2.13 r1665067
> 
> :jmRun FAILED

FAILURE: Build failed with an exception.

**Comment by djangofan** [comment]
Currently the plugin packs don't properly load. I would be surprised if you
got that extractor to work.  There is a bug reported on the issue.

**Comment by foragerr** [comment]
related to #3. Thanks for bringing this up.

xstream cant find some classes, probably a classpath issue - I will try to get to this, this weekend.

**Comment by foragerr** [comment]
Directly added jp@gc jars to JMeter search_paths - should fix this issue. Please verify.

Fixed in 1.0.2-SNAPSHOT
will be released in 1.0.2

**Comment by djangofan** [comment]
Actually, wasn't it fixed in 1.0.3-2.13-SNAPSHOT?
