### ISSUE TITLE
Support -q (--addprop) JMeter option

### ISSUE THREAD

**Issue by DKroot** [jmeter-gradle-plugin/jmeter-gradle-plugin#39]
I could not find a way to pass -q (--addprop) to JMeter. I have a particular use case to use this JMeter option.

**Comment by foragerr** [comment]
This should be straightforward to add, I'll look into it. 

Can you elaborate your use case though? I'm curious!

**Comment by DKroot** [comment]
Sure. I think it could be quite common,

I customized all of JMeter settings that I need in `user.properties`. This file is common to the project and is committed to version control. I do have command-line parameters that I pass via `-P` to `jmUserProperties` to JMeter `-J`. I have to pass production user credentials. On CI server, I pass them via masked Gradle properties.

However, when I develop locally, I don't want to add credentials to `user.properties` in version control for security reasons. Neither I want to type -P parameters all the time. What would work best for me is `private.properties` file, which is excluded from version control.

That's where `-q` comes into play. It works great in this case.

**Comment by foragerr** [comment]
Added

```
jmeter{
    jmAddProp = file('path/to.properties')  //maps to -q, --addprop
}
```

**Comment by DKroot** [comment]
Thanks! Testing it now...
