### ISSUE TITLE
HTML report fails to generate

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#4]
For sample project here: https://github.com/djangofan/launch-jmeter

**Comment by foragerr** [comment]
@djangofan if you want to re-test this, please use 
`"net.foragerr.jmeter:jmeter-gradle-plugin:0.1.3-2.13"` from bintray

**Comment by djangofan** [comment]
@foragerr   Ok, I haven't used bintray before but I will try it.  I found your jmeter-gradle-plugin  "organization" and found your latest release and instructions in the README.   I'll try it asap.

**Comment by foragerr** [comment]
Just bump the version number in buildscript -> dependencies -> classpath in your build.gradle to `0.1.3`. I believe you are currently using `0.1.1`

**Comment by djangofan** [comment]
@foragerr   Ok, the reports are now generating but I am having these issues still:
1.  The "jmeter.save.saveservice.timestamp_format=none"  seems to be ignored.  I am still only getting a report.html that is stamped with a timestamp.
2.  Using "jmeter.save.saveservice.output_format=csv"  causes report.html to be blank.

**Comment by foragerr** [comment]
I'll look into no.1

no.2 is not easy - currently the html report is generated by transforming xml using xslt. CSV will need a whole new transformer - Feel free to create a new issue, but i'll probably put it on ice for later, and add a note in documentation that if you need HTML reports, you _have_ to do output=xml

**Comment by djangofan** [comment]
I tried your version 0.1.5-2.13 this morning and there is still a timestamp on the report file:
test2.jmx-20150715-0804-report.html

Should I start a new bug/issue instead of tracking in this thread?

**Comment by foragerr** [comment]
Yes please. I haven't fixed it yet.

**Comment by djangofan** [comment]
Ok, this thread is closed.  I'll open a new one.

**Comment by djangofan** [comment]
@foragerr Using version 0.5.6  of the plugin,  when you execute  'jmRun' task  the .xml gets generated but the .html output and extended artifacts do not get auto-generated and you need to explicitly run 'jmReport' task to get the reports.    This is ok, but shouldn't the default behavior for 'jmRun' be to also generate results output?

**Comment by foragerr** [comment]
no, that'll get fixed when #10 and #12 are closed.
