### ISSUE TITLE
jmGui does not open a single .jmx file whereas jmRun runs it fine

### ISSUE THREAD

**Issue by DKroot** [jmeter-gradle-plugin/jmeter-gradle-plugin#40]
I don't specify JMeter test file, I have just a single .jmx in `src/test/jmeter`. `jmRun` runs it just fine, but `jmGui` just opens blank JMeter. Per documentation, the idea was to open .jmx, wasn't it?

https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/wiki/Getting-Started

"Edit JMeter files

By default the plugin will search for *.jmx files in src/test/jmeter. You can launch the UI end edit your files by running:

gradle jmGui"

**Comment by foragerr** [comment]
Hmm that wiki entry is rather ambiguous, the code to launch GUI with jmx loaded was never there. You think there is value in doing that?

Question is, if the project contains multiple .jmx files, which would the GUI open by default? (jmRun executes multiple .jmx files if they're available)

**Comment by DKroot** [comment]
Yes, I do think it would be valuable.

I'm currently the only one on our project who is familiar with JMeter, To share knowledge and get people started to develop JMeter tests, I would rather ask them to run `>gradle jmGui`, which is simple enough to remember. It would be valuable because they would not need to download and install JMeter.

I also would be able to use it myself for daily development. I had to create a custom shell script, which I use instead of `>gradle jmGui`. If you make the change, I can get rid of this because `>gradle jmGui` is short enough to type. Another reason why I use custom script currently is https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/39.

You can open the first found file alphabetically as a convention if the test files are not specified. Otherwise, the first from the list of `jmTestFiles` would do. Many people would have only a single test file to speak of.
