### ISSUE TITLE
include third party jar files

### ISSUE THREAD

**Issue by hypervisorfdi** [jmeter-gradle-plugin/jmeter-gradle-plugin#43]
My jmeter tests require third party jars, is there any documentation on how to get these jar files on classpath for this plugin?

**Comment by hypervisorfdi** [comment]
Found a way to do so, sorry for opening this

**Comment by foragerr** [comment]
Hi, as with regular jmeter, you could set `user.classpath` or `plugin_dependency_paths` using either `jmUserProperties` or `jmUserPropertiesFiles`

You could also try `jmPluginJars`. This option was intended to be used to add jmeter plugin jars to the class path. Don't see why you can't add any arbitrary jars with it though.
