### ISSUE TITLE
How to pass user defined variables

### ISSUE THREAD

**Issue by ssuummit** [jmeter-gradle-plugin/jmeter-gradle-plugin#44]
Hi,
In my jmx file i have few user defined variables whose value I need to pass while running test through command gradle jmRun.

For e.g. ${__P(idempotentKeySize,128)}, ${__P(metaDataSize,1024)}, ${__P(serverIP,127.0.0.1)} are few variables.

While running through jmeter non gui mode i can pass values with command like jmeter -n -t xyz.jmx -JidempotentKeySize=1111 -JmetaDataSize=1111 -JserverIP=1.1.1.1

How can I pass user defined values with this plugin? I have checked documentation but couldn't figure out how should I pass it in jmRun command.

What I got from documentation is I need to define jmUserProperties in build.gradle. Can you provide an example for how to define it in gradle file and how to pass property value from jmRun command.

If i'll define jmUserProperties like below in build.gradle file then how can I modify/pass property value while executing jmRun. 

jmeterUserProperties= ["SERVER=1.1.1.1",
                    "metaDataSize=11111"]

**Comment by foragerr** [comment]
`jmeterUserProperties` is the same as the `-J` flag. Does using `${__P(metaDataSize,1024)}` not work for you?

**Comment by ssuummit** [comment]
I am getting error if I am using ${__P(metaDataSize,1024)} in jmx file and then passing its value through while running test.

Command:
gradle jmRun -Djmxscripts=xyz.jmx -JmetaDataSize=12

Error:
Problem configuring task :jmRun from command line.

> Unknown command-line option '-J'.

**Comment by foragerr** [comment]
I meant use `jmeterUserProperties` in build.gradle and that's it. You need to send in values from the commandline? Is this for CI, like jenkins or something?

There currently isn't support for -J props from the command line, maybe I should add it. There is a sort of workaround though.: Use `-P` properties in the command line and assign them to `jmeterUserProperties` explicitly in build.gradle:

```
jmeterUserProperties << "metaDataSize=" + project.property('metaDataSize')
```

and then run:

```
gradle jmRun -PmetaDataSize=12
```

**Comment by ssuummit** [comment]
Yes I need it to pass value from jenkins.
For now I have done it using -D option and assigning it to jmeterUserProperties explicitly in build.gradle.

 jmUserProperties = ["metaDataSize ="+System.getProperty('metaDataSize','128')]

and then in run

gradle jmRun -DmetaDataSize=11

**Comment by foragerr** [comment]
Thanks for the update! I will close this issue now, but I'm raising a new issue for an enhancement request here: #45

**Comment by rinoto** [comment]
As a workaround to pass any number of `-P` params, you can add these two lines to the `jmeter` section of `build.gradle`:

```
  jmUserProperties = new ArrayList();
  project.properties.each{ k, v -> jmUserProperties << "${k}=" + "${v}" }
```
