### ISSUE TITLE
When using xpath extractor, test fails, but build does not fail

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#48]
#47 reports a problem when using xpath extractor in a jmeter test plan. Due to xml-apis version conflict, test execution fails. But the failure does not result in a gradle build failure.

**Comment by kallekarlberg** [comment]
Can this be worked around by exluding xml-apis 2 somehow, or will this break something else?

**Comment by kallekarlberg** [comment]
I guess this causes error:
2016/03/31 22:05:47 ERROR - jmeter.threads.JMeterThread: Error processing Assertion  java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
....

**Comment by foragerr** [comment]
You can exclude the breaking version and then include the good version. Or alternatively, you can tell gradle's resolution strategy to always force a particular version. Which is what I suggested [here](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/47#issuecomment-202172707)

However this particular issue isn't about xml-apis, but rather the fact that when you get the NoClassDefFoundError, gradle build doesn't fail, and it should IMO.

**Comment by foragerr** [comment]
Changed defaults for `ignoreErrors` and `ignoreFailures` to false, so failing builds on errors/failures is default behavior
