### ISSUE TITLE
xml-apis dependency issue

### ISSUE THREAD

**Issue by sbennettmcleish** [jmeter-gradle-plugin/jmeter-gradle-plugin#49]
Using the plugin causes non-related dependencies to fail, specifically the following:

> Could not resolve org.apache.commons:commons-collections4:4.0
>     > org/w3c/dom/ElementTraversal

This is due to a version conflict of the xml-apis library. Version 2.0.2 of this library is what is included via transitive dependencies of this plugin (mainly avalon-framework:avalon-framework-impl:4.3). However the versioning of xml-apis is out of order, 2.0.2 was released in 2002, whereas the current version 1.4.01 was reelased in 2009. See here: http://mvnrepository.com/artifact/xml-apis/xml-apis.

Locally, I've added the following to the build.gradle and it forces the dependency resolution to choose the 1.4.01 version (the latest) which includes the org/w3c/dom/ElementTraversal interface that is missing in the 2.0.2 version.

```
configurations {
    all {
        resolutionStrategy {
            force 'xml-apis:xml-apis:1.4.01'
        }
    }
}
```

If this could be added to the build.gradle of this project that would be great.

**Comment by foragerr** [comment]
Fixed
