### ISSUE TITLE
No such property: jmUserPropertiesFiles for class: net.foragerr.jmeter.gradle.plugins.JMPluginExtension_Decorated

### ISSUE THREAD

**Issue by sumangongali** [jmeter-gradle-plugin/jmeter-gradle-plugin#53]
I have issue found .. first try here ..

```
Executing command: "tasks"
Starting Build
Compiling initialization script 'C:\Users\sgongali.ORADEV\AppData\Local\Temp\refresh-tasks-init-script3089449122778499005.gradle' using SubsetScriptTransformer.
Compiling initialization script 'C:\Users\sgongali.ORADEV\AppData\Local\Temp\refresh-tasks-init-script3089449122778499005.gradle' using BuildScriptTransformer.
Settings evaluated using settings file 'C:\master\settings.gradle'.
Projects loaded. Root project using build file 'C:\JMETER\gradle\build.gradle'.
Included projects: [root project 'gradle']
Evaluating root project 'gradle' using build file 'C:\JMETER\gradle\build.gradle'.
Compiling build file 'C:\JMETER\gradle\build.gradle' using SubsetScriptTransformer.
Compiling build file 'C:\JMETER\gradle\build.gradle' using BuildScriptTransformer.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\JMETER\gradle\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'gradle'.
> No such property: jmUserPropertiesFiles for class: net.foragerr.jmeter.gradle.plugins.JMPluginExtension_Decorated

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'gradle'.
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
```

my build file:

```
buildscript {

    repositories {
        maven {
        url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.net.foragerr.jmeter:jmeter-gradle-plugin:1.0.4-2.13"
    }
}

apply plugin: "net.foragerr.jmeter"

jmeter {
    jmTestFiles = [file("src/test/jmeter/JSR223 Sampler.jmx")] 
    jmUserPropertiesFiles = [file("src/test/jmeter/user.properties")] 
    enableExtendedReports = true 
}
```

Also please let me know some where i can see advanced build where i can pass

extra properties file , extra arguments , env related variables

what ever the examples in the home page is not sufficient.

**Comment by foragerr** [comment]
Can you try `jmSystemPropertiesFiles` instead of jmUserPropertiesFiles?

**Comment by foragerr** [comment]
see here: https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/wiki/Advanced-Usage

**Comment by sumangongali** [comment]
Thanks,
please change it in   http://jmeter.foragerr.net/
`jmeter {
  jmTestFiles = [file("src/test/jmeter/test2.jmx")] 
  jmUserPropertiesFiles = [file("src/test/jmeter/user.properties")] 
  enableExtendedReports = true 
}`

My Request:

I have invested so much time in to kulyas great code piece,  Now i hope this would also cross that reputation. Had spent all 3 hours in open and closed issues here.

Here are my questions 

How to send private.propties, user properties, System.properties and Heapsize properties

private properties are TestPlan specific properties
user properties and system.properties and jmeter.properties are as it own purpose.

I am not giving any command line options, all i want to store in properties file  and run them. 

Thanks in advance.

**Comment by sumangongali** [comment]
Using advanced option's

```
jmeter {
  jmTestFiles = [file("src/test/jmeter/JSR223 Sampler.jmx")]
  jmPropertyFile= file("src/test/jmeter/props/private.properties")
  jmSystemPropertiesFiles  = [file("src/test/jmeter/user.properties"),file("src/test/jmeter/jmeter.properties")] 
  enableExtendedReports = true 
}
```

Error :  

```
Using
   jmeter-gradle-plugin version:1.0.4-2.13
   jmeter version:2.13
   jmeter jp@gc plugins version:1.3.0

:jmInit (Thread[main,5,main]) completed. Took 0.164 secs.
:jmRun (Thread[main,5,main]) started.
:jmRun
Executing task ':jmRun' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Executing jMeter test : C:\JMETER\gradle\src\test\jmeter\JSR223 Sampler.jmx
JMeter is called with the following command line arguments: [-n, -t, C:\JMETER\gradle\src\test\jmeter\JSR223 Sampler.jmx, -l, C:\JMETER\gradle\build\jmeter-report\JSR223 Sampler.jmx-20160421-2259.xml, -p, C:\JMETER\gradle\src\test\jmeter\props\private.properties]
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: -S
```

**Comment by foragerr** [comment]
I've been meaning to write a migration guide from kulya's to this plugin. Just never found the time. If you'd be kind enough to maybe expand on this page a little bit, I would appreciate it!

https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/wiki/Migrating-from-kulya-jmeter-gradle-plugin

Corrected jmSystemPropertiesFiles on the homepage, thanks for finding the error!

**Comment by sumangongali** [comment]
I am willing to do what i can , but what ever the limited knowledge i have i am posting it as well. I am willing to Learn,and Help :-)

**Comment by foragerr** [comment]
How are your private and user properties different? is it possible to combine them both into 1 file?

I'm looking into the -S error.

**Comment by sumangongali** [comment]
Private values are plan specific values , User specific are not yet determined but we use it for user specified values,  by the way , if -S error is exists then HEAP specific parameters also not possible right.

Could you please give me example how to specify heap specific values .

**Comment by foragerr** [comment]
jmSystemPropertiesFiles  is definitely a defect, raising a separate issue for that. #55

Can you check if this helps for private.properties? https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/39

**Comment by sumangongali** [comment]
Thanks, Can you point me any sample that shows result graphs using this plugin , i can test it very quickly and report if any usable issues.

**Comment by foragerr** [comment]
you can directly set maxHeapSize by setting 

```
jmeter{
  maxHeapSize = STRING
}
```

this will be added to the jmeter java process as : `-XmsSTRING -XmxSTRING` both. I don't believe this is documented so far - though it should be.

**Comment by foragerr** [comment]
So putting it all together, you should be doing:

```
jmeter {
  jmTestFiles = [file("src/test/jmeter/test.jmx")]
  jmPropertyFile= file("src/test/jmeter/user.properties")
  jmAddProp = file("src/test/jmeter/props/private.properties")
  //jmSystemPropertiesFiles  = [file("src/test/jmeter/jmeter.properties")] <--this doesn't work currently - will update shortly
  enableExtendedReports = true 
  maxHeapSize = '1024m'
}
```

**Comment by sumangongali** [comment]
I am done with editing 

 maxHeapSize = STRING        -XmsSTRING -XmxSTRING  (usage maxHeapSize= "-Xms1024  -Xmx4096")

https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/wiki/Advanced-Usage

**Comment by sumangongali** [comment]
Sorry  I feel i am done wrong  on heapSize

**Comment by foragerr** [comment]
I should probably add a `minHeapSize` parameter as well.

to generate reports, you have to run a separate task `jmReport` after `jmRun` executes successfully. reports are generated in `$rootDir/build/jmeter-report`. Again, I should probably document sample reports somewhere.

**Comment by sumangongali** [comment]
Can I go and delete those lines which i have added in 

maxHeapSize = STRING -XmsSTRING -XmxSTRING (usage maxHeapSize= "-Xms1024 -Xmx4096")

https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/wiki/Advanced-Usage

**Comment by foragerr** [comment]
Yes, feel free to edit it, it is a wiki afterall!

**Comment by foragerr** [comment]
If you got everything you need for now except jmSystemPropertiesFiles , go ahead and close this issue.

**Comment by sumangongali** [comment]
Thanks a lot , also raising lot of issues :-)

**Comment by foragerr** [comment]
more issues is good!
