### ISSUE TITLE
add minHeapSize parameter

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#56]

**Comment by sumangongali** [comment]
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid initial heap size: -Xmsnull
:jmRun FAILED
:jmRun (Thread[main,5,main]) completed. Took 0.339 secs.

If its not provided could you please make default value , if its provided please override it.

**Comment by sumangongali** [comment]
Also observed if the minHeap is mentioned is grater than maxHeap error is throwing error that is good.

could you please  make it as   <List> File jmPropertyFile ,instead of single file  " File jmPropertyFile             //maps to -p, --propfile

**Comment by foragerr** [comment]
oops Thanks for testing the changes!
I have some time to look at this later this evening. I'll fix the minHeap default value.

I'm not sure I understand the comment about jmPropertyFile, it also seems like a separate issue from minHeap. Can you please raise a new issue and add some details if you can?

**Comment by sumangongali** [comment]
Yes its a sepearate issue rasing another one.

**Comment by sumangongali** [comment]
also attached results.xml

On Mon, Apr 25, 2016 at 6:17 PM, RaGe notifications@github.com wrote:

> oops Thanks for testing the changes!
> I have some time to look at this later this evening. I'll fix the minHeap
> default value.
> 
> I'm not sure I understood the comment with jmPropertyFile, it also seems
> like a separate issue from minHeap. Can you please raise a new issue and
> add some details if you can?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/56#issuecomment-214299962

## 

Regards,
-Suman
