### ISSUE TITLE
No JSON support on this plugin by default

### ISSUE THREAD

**Issue by sumangongali** [jmeter-gradle-plugin/jmeter-gradle-plugin#57]
I realized, In order to have groovy and json and other stuff exisits in plugin 

the following jars must be in place 

 jmeterPluginJars = ["groovy-all",
                        "jmeter-plugins-standard",
                        "jmeter-plugins-common",
                        "jmeter-plugins-extras",
                        "jmeter-plugins-extras-libs", 
                        "jmeter-plugins-webdriver"]

for "groov-all" i had corresponding classpath dependency --> classpath "org.codehaus.groovy:groovy-all:2.4.3"

   how to have further in place , I I need json in place. I feel it is available in 

http://jmeter-plugins.org/wiki/ExtrasWithLibsSet/

so for users who use this plugin and novice to gradle will look for this information 

the each set in  http://jmeter-plugins.org/  and the corresponding classpath dependencies.

some how this plugin should provide them in place.

**Comment by foragerr** [comment]
I have these currently:

```
compile("kg.apc:jmeter-plugins:${jmPluginVersion}")
compile("kg.apc:jmeter-plugins-standard:${jmPluginVersion}")
compile("kg.apc:jmeter-plugins-extras:${jmPluginVersion}")
compile("kg.apc:jmeter-plugins-common:${jmPluginVersion}")
```

I'll add the remaining and do a release. Just to keep things light weight for people not using these additional plugins, I also think there should be a flag to turn these on or off.

**Comment by sumangongali** [comment]
i am interested to document it . i know medium level gradle and groovy , hence i may need more information to understand , please cope up . 

So what would be the corresponding on and off flag needs to be used in build file .
if that on and off feature available now? then how to use it in build section . or if its not available then how to make them available and what code must present in build file.

**Comment by foragerr** [comment]
The on/off flag doesn't exist right now, I added a [new issue for this feature enhancement](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/58), it will have to be done in the plugin code. More specifically, [this part of the code](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/blob/master/src/main/groovy/net/foragerr/jmeter/gradle/plugins/TaskJMInit.groovy#L116) should also check for a flag value before adding plugin jars to jmeter `search_paths`

I might do it after I close this issue.

**Comment by sumangongali** [comment]
i found something will this work ?  by adding 

classpath:kg.apc:jmeter-plugins-extras:1.3.1    to class path dependencies will those JSON feature will i get it.

**Comment by foragerr** [comment]
I already have plugins-extras, you probably need jmeter-plugins-extras-libs

**Comment by sumangongali** [comment]
Yes exactly .. what is the code peace i need to add it to class path dependency to make it available at jmRun, jmGui

**Comment by sumangongali** [comment]
will this work ?
classpath:kg.apc:jmeter-plugins-extras-libs:1.3.1

**Comment by sumangongali** [comment]
Done using this , But what ever was added as a fix and those exclude part is only applicable to complile time i feel .. for run time also we need to exclude them?

working part

  classpath(group: 'kg.apc', name: 'jmeter-plugins-extras-libs', version: '1.3.1') {
        exclude group: 'commons-math3', module: 'commons-math3'
        exclude group: 'commons-pool2', module: 'commons-pool2'
    }

**Comment by foragerr** [comment]
Just released 1.0.5, you shouldn't have to add anything extra to the class path, JSON extract should work out of box. Can you please try and let me know if you see any issues?

https://plugins.gradle.org/plugin/net.foragerr.jmeter

**Comment by foragerr** [comment]
and yes, the excludes are required for compile, or runtime. That is a workaround for a defect in jmeter 2.13, where they added wrong dependencies in their published pom https://bz.apache.org/bugzilla/show_bug.cgi?id=57748

**Comment by sumangongali** [comment]
would you please confirm on this . The expanded version must be availble in the gradle.build right?

i.e., suppose if i dont provide   ${jmPluginVersion}  actual value(1.3.1) these jars not included right?

compile("kg.apc:jmeter-plugins:${jmPluginVersion}")
compile("kg.apc:jmeter-plugins-standard:${jmPluginVersion}")
compile("kg.apc:jmeter-plugins-extras:${jmPluginVersion}")
compile("kg.apc:jmeter-plugins-common:${jmPluginVersion}")

**Comment by foragerr** [comment]
These dependencies are already added in the plugin build.gradle. As a plugin user (v1.0.5 onwards) you do not have to add these dependencies to your project.

If jmPluginVersion is not defined gradle will throw an error on the line: `compile("kg.apc:jmeter-plugins:${jmPluginVersion}")` and the build will fail.

**Comment by sumangongali** [comment]
Thanks for your confirmation !!!

On Mon, Apr 25, 2016 at 10:17 PM, RaGe notifications@github.com wrote:

> These dependencies are already added in the plugin build.gradle. As a
> plugin user (v1.0.5 onwards) you do not have to add these dependencies to
> your project.
> 
> If jmPluginVersion is not defined gradle will throw an error on the line:
> compile("kg.apc:jmeter-plugins:${jmPluginVersion}") and the build will
> fail.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/57#issuecomment-214437568

## 

Regards,
-Suman
