### ISSUE TITLE
TODO: Extended reports should go into a more descriptively named sub-folder

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#6]
candidate: `jmeter-extended-reports` instead of just `reports`

**Comment by djangofan** [comment]
Also, can you add an HTML file in that report folder that loads and shows all images and .csv file links on one page?

Also, I noticed you created a 'https://github.com/jmeter-gradle-plugin/jmeter-analysis-gradle-plugin' project.   Are you intending to break out the extended reports feature into that separate project?

**Comment by foragerr** [comment]
> Are you intending to break out the extended reports feature into that separate project

No, I meant for that project to be a gradle version of this maven plugin: https://github.com/afranken/jmeter-analysis-maven-plugin

**Comment by foragerr** [comment]
Does it make sense to drop the two kinds of reports we do now, and just have 1 kind of report, a html file, with all the graphs, csvs in it?

**Comment by djangofan** [comment]
@foragerr   I don't think so.  The reason being that if you want to use the "Jenkins HTML Publisher" plugin, it only works to archive single file artifacts at a time  (and only when those artifacts always have a constant name i.e. no time stamp on them).     If you create a larger HTML page that has a index.html and links to external images and csv files, then the HTML Publisher cannot archive them as a group of files.   

More specifically, I might want "HTML Publisher" to archive only the 'PROJECT-report.html'  and also the 'prettygraph.png'  file.  Then, when I click on individual builds in Jenkins build history, those 2 files are archived and easy to view.   If there are 10 .png files for each build, the Jenkins user has a choice of which of the 10 files he wants to consistently archive: none of them, some of them, or all of them.
