### ISSUE TITLE
create extended cleanReports

### ISSUE THREAD

**Issue by sumangongali** [jmeter-gradle-plugin/jmeter-gradle-plugin#62]
createExtended reports must clean every log and results literally there must not be any log including jmeter.log

**Comment by foragerr** [comment]
do you mean `jmclean`?

**Comment by sumangongali** [comment]
Yes jmClean only clears the current run reports ,but a clear clean is required as well.

**Comment by foragerr** [comment]
Agreed

**Comment by foragerr** [comment]
Unable to reproduce:

so the task `jmClean` currently deletes the entire jmeter-report directory and recreates it - this deletes everything including jmeter log. Added an additional line to delete jmeter log even if it's location is customized.

**Comment by foragerr** [comment]
Closing this for now, please feel free to reopen if I misunderstood the issue report.
