### ISSUE TITLE
provide selected  graph options as list

### ISSUE THREAD

**Issue by sumangongali** [jmeter-gradle-plugin/jmeter-gradle-plugin#63]
Presently it has only Graph generator option for jp@gc , but when user attached a Graph results why it is not generating as it wanted .

i.e., i have a project which has a GraphResults listener is enabled. but graph is not getting generated.

did i miss any or feature itself is not available.

if available what is the procedure.

Thanks In advance.

**Comment by sumangongali** [comment]
yea after digging in to code , I see its a static final List , hence no more additional graphs :-)  , can you add all graph options and provide user to pick relevant from the list  as a feature .. this time i needed GraphResults  listener :-(  , I feel this is nice here to enhance.

public static final List<String> pluginTypes = Arrays.asList(
            "ResponseTimesOverTime",
            "HitsPerSecond",
            "BytesThroughputOverTime",
            "LatenciesOverTime",
            "ResponseCodesPerSecond",
            "TransactionsPerSecond",
            "ResponseTimesDistribution",
            "ResponseTimesPercentiles",
            "ThreadsStateOverTime",
            "TimesVsThreads",
            "ThroughputVsThreads"
    );

Question 2:

I also Noticed that the above graph options are plugin graph options but not standard jmeter built-in graphs are not generated, if standard jmeter buit-in graph listeners also takes the same input i feel we can add them as well here. 

if that is expensive now , can you provide me code block sample how to generate automatically from my build file those graphs .

**Comment by foragerr** [comment]
@sumangongali do you know of a way to produce GraphResults graph from jmeter commandline?

**Comment by sumangongali** [comment]
Not Sure How to generate. Looking fro a way .

On Thu, Apr 28, 2016 at 7:04 AM, RaGe notifications@github.com wrote:

> @sumangongali https://github.com/sumangongali do you know of a way to
> produce GraphResults graph from jmeter commandline?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/63#issuecomment-215281698

## 

Regards,
-Suman

**Comment by foragerr** [comment]
As far as I can tell, there doesn't seem to be a way - which means the plugin wont be able to automatically generate that graph for you. Your best bet would be to run `jmGui` to launch JMeter GUI, and load the result file into the graph listener to view the graph.

Jmeter 3.0 has quite neat looking reports, see this page for details: http://home.apache.org/~milamber/jmeter-3.0RC3/docs/changes.html

The plan is to add [support for JMeter 3.0 soon](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/64).

**Comment by foragerr** [comment]
Replacing jmreport output with JMeter 3.0's dashboard instead. #wontfix
