### ISSUE TITLE
Support of upcoming JMeter 3.0

### ISSUE THREAD

**Issue by pmouawad** [jmeter-gradle-plugin/jmeter-gradle-plugin#64]
Hello,
First thanks for this very interesting plugin.

Second, do you plan to support JMeter 3.0 mainly:
- New command line options related to JMeter reports
- Generation of Report as provided by 3.0 

For information RC3 of 3.0 which should hopefully be the next 3.0 is expected to start this wednesday, votes will be pending for 72 hours then release should come if votes are positive

Thanks
@philmdot

**Comment by foragerr** [comment]
Philippe, I absolutely want to add support for 3.0 as soon as possible.
I'll take a look at RC3 documentation.

**Comment by sumangongali** [comment]
Exited !! thanks for pointing this , cool features to explore .. please let us know asap we have new plugin here..

**Comment by foragerr** [comment]
@sumangongali I already started work on integrating 3.0. I have the plugin working with JM3.0, but I need to add the new reports feature before I release. 

The current code is in this branch:
https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/tree/JMeter3.0

**Comment by sergebug** [comment]
I'm able to run current jMeter 3 via plugin using release dependencies. In case I have some time on my hands to look into it, Is there something else preventing v3 from release?

**Comment by foragerr** [comment]
@sergebug I just haven't gotten around to adding some sort of access to the new reports feature. Otherwise running a test using JM3.0 works with the branch I linked above.

**Comment by foragerr** [comment]
Maybe I should release a .beta version of 3.0, just so it is out there and usable sans reports.

**Comment by sergebug** [comment]
@foragerr Could you elaborate regarding new reports feature? Are you talking about new reports from this plugin (didn't use those much) or something like new dashboards? http://jmeter.apache.org/usermanual/generating-dashboard.html
P.S. Thumbs up for the beta

**Comment by foragerr** [comment]
Not something like, exactly those dashboards!

Wanted to add a task or modify existing report task to generate that dashboard after a test run.

**Comment by johnwanggithub** [comment]
Wish to see the next release will contain this and issue 79 fix asap. thanks a lot in advance

**Comment by foragerr** [comment]
@johnwanggithub v1.0.7-2.13 released, containing #79 fix.

**Comment by foragerr** [comment]
released [1.0.7-3.0-BETA](https://plugins.gradle.org/plugin/net.foragerr.jmeter/1.0.7-3.0-BETA)

**Comment by johnwanggithub** [comment]
so great! will try asap @foragerr thanks!

**Comment by pmouawad** [comment]
Thanks . Is 3.0 support complete or still in progress ?
It would be nice if you had some release notes page showing what new version contains.
Or you could use GITHUB milestone informations for that.

Thanks for your work.

**Comment by djangofan** [comment]
Keep in mind that there were more updates for reporting in JMeter 3.1 ...

**Comment by foragerr** [comment]
support for 3.3 added in newest version.
