### ISSUE TITLE
logfile text should be appended not overwritten on (jmRun | jmInit)

### ISSUE THREAD

**Issue by jmattheis** [jmeter-gradle-plugin/jmeter-gradle-plugin#66]
When starting multiple (jmInit | jmRun, dont know which one)-task in one gradle execution, the logfile get cleaned on new task execution. It should be appended and only deleted/cleared on `jmClean`.

**Comment by foragerr** [comment]
Hmm.. This is default jmeter behavior. If you start a second run jmeter overwrites jmeter.log

I see value in what you're suggesting, but I'm wondering how much the plugin should deviate from default behavior.

BTW jmrun overwrites the log file, and really it is the jmeter process that overwrites it.

**Comment by jmattheis** [comment]
Okay, can be closed from my side, as it is jmeters fault.
