### ISSUE TITLE
jmRun. Logs in commandLine

### ISSUE THREAD

**Issue by romankh3** [jmeter-gradle-plugin/jmeter-gradle-plugin#76]
In JMeter we have "-j /dev/stdout" and this additional tools provide show logs in commandLine.
How can I make it in this plugin?

**Comment by foragerr** [comment]
Hi, currently jmeter log is written to `$buildDir/jmeter-report` as a `.log` file. Would tailing this file not be sufficient?

**Comment by romankh3** [comment]
You are right, i can find logs in that folder.  But also i want to see logs in command line.  It works in jmeter when you write "jmeter -n -t test.jmx -j /dev/stdout "

**Comment by romankh3** [comment]
How can i do this?

**Comment by foragerr** [comment]
I can't think of a straightforward way to support this from the plugin, in a way that works on linux as well as windows. Since jmeter logs are written to file anyway, I would suggest that you do `tail -f` on the log file to view it in real-time.

I'm closing this issue as will not implement.

**Comment by foragerr** [comment]
I added showing test summarizer to gradle output in the latest dev build
