### ISSUE TITLE
Let build fail if there were errors

### ISSUE THREAD

**Issue by mathume** [jmeter-gradle-plugin/jmeter-gradle-plugin#80]
It'd be nice if a build could be marked as FAILED if

```
scanner.scanForProblems(file)
```

returned true in `rc/main/groovy/net/foragerr/jmeter/gradle/plugins/TaskJMRun.groovy`.

Or is there another way to achieve this with gradle?
#48 describes this problem, too (unrelated to the xml-apis)

**Comment by foragerr** [comment]
Fixed in dev build [1.0.8-3.0-SNAPSHOT](https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/libs-snapshot/net/foragerr/jmeter/jmeter-gradle-plugin/1.0.8-3.0-SNAPSHOT)

**Comment by foragerr** [comment]
set `ignoreErrors=false` and/or `ignoreFailures=false` they're both true by default. I reckon I should change default behavior to fail a build.

**Comment by foragerr** [comment]
Changed default behavior to fail on error/failure
