### ISSUE TITLE
Test threads not finishing on their own when running jmRun

### ISSUE THREAD

**Issue by jfosqa** [jmeter-gradle-plugin/jmeter-gradle-plugin#81]
I've configured my gradle.build file to utilize my user.properties file for JMeter. When I run jmRun, my test file fails to close any threads and when I manually kill the task it logs the threads finishing. 

When I execute jmGui, the threads finish on their own.

The same test file executes without issue via the JMeter UI and command line when I use my local JMeter instance (checked with 2.13 and 3.0).

**Comment by jfosqa** [comment]
the issue with the RegEx not resolving is resolved. Not sure why, but the gradle-jmeter build doesn't like Body (as document) for field to check. 

Threads not finishing is still an issue. Will update main report.

**Comment by foragerr** [comment]
Hmm, could you provide a simplified project to reproduce this issue? This plugin just runs jmeter in a separate java process, not different from running jmeter from the command line. There isn't much else to it.

**Comment by jfosqa** [comment]
That's what I thought, that's why this issue is so odd.

Let me try to build a test around an accessible site and see if I can reproduce the issue there. The test is dependent on a site that can't be publicly deployed.

**Comment by jfosqa** [comment]
Just pulled in the 1.0.7-3.0-BETA - and all of the threads terminate as expected with jmRun. Will debug this one locally and try to find the culprit.

Thanks.
