### ISSUE TITLE
How to run only a single jmx file thru jmRun gradle task?

### ISSUE THREAD

**Issue by ak120684** [jmeter-gradle-plugin/jmeter-gradle-plugin#82]
I know there is a way to specify files we'd like to run as below.
"jmTestFiles = [file("src/test/jmeter/jmeterscripttorun.jmx")]"
Also, we can use "excludes = ["AddRandomProductsToCart.jmx", "CheckoutFlowTest.jmx"]" to exclude some desired files from src>test>jmeter dir

But, by default, jmRun cmd runs all the files in the root dir excluding the ones I have in "excludes".

However, I want to run one particular file and not others that are not excluded.

This is because I am running over a CI server, where there are different branches for different tests.

**Comment by foragerr** [comment]
Have you tried setting `testFileDir` to some location other than `src/test/jmeter` so no jmx files are picked up and then add only the ones you want using `jmTestFiles` ?

**Comment by foragerr** [comment]
Hi, I'm closing this as there's no response from you. Feel free to reopen if needed.
