### ISSUE TITLE
CSV Output

### ISSUE THREAD

**Issue by g1ps** [jmeter-gradle-plugin/jmeter-gradle-plugin#83]
Hi,

How do I turn on CSV output? Uncommenting 

```
jmeter.save.saveservice.output_format=csv
```

in jmeter.properties doesn't work. Neither

```
jmUserProperties =  ["jmeter.save.saveservice.output_format=csv"]
```

nor

```
jmSystemProperties =  ["jmeter.save.saveservice.output_format=csv"]
```

work. What have I missed?

Thanks.

**Comment by foragerr** [comment]
There currently isn't a way to do that. The report feature depends on the results being in XML, so the property is currently hard set to XML. Guess I could add an option to do CSV, but it will break the jmreport task.

**Comment by g1ps** [comment]
Ah. That should be reported loud and clear somewhere in the introduction. I've spent some time researching and getting this to work in our system and this may now compromise my ability to use it. Not good.

Thanks.

**Comment by g1ps** [comment]
There is a chance we won't need your reports, so I will reply re: the option to add it, thanks.

**Comment by foragerr** [comment]
> That should be reported loud and clear somewhere in the introduction

Feel free to submit a pull request for readme.md, or make a wiki entry.

**Comment by g1ps** [comment]
Sure, OK.

**Comment by g1ps** [comment]
Hi again. If you could add the CSV output option, that would be much appreciated. I imagine that's fairly trivial. We'd like to be able to generate both, if possible, at times. I don't know if that's something that jMeter supports at a base level, or not. Thanks also for the prompt replies. Much appreciated.

Cheers.

**Comment by foragerr** [comment]
It's one or the other, JMeter does not support both formats for a single test.

**Comment by g1ps** [comment]
I suspected that. That's fine. Thanks.

**Comment by g1ps** [comment]
Hi,

Is there an ETA on this? I don't mean to pressure you I just need to know whether to wait or do the work to parse the XML.

Thanks.

**Comment by foragerr** [comment]
Already [Fixed](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/commit/248b1d59aeb8b7ad0055ba784e7e1483da6d6922) in snapshot. Sorry, forgot to update this issue.

**Comment by g1ps** [comment]
OK, thanks. How do I enable it?

Why is there no commit here on Github? I can't even check what's changed. Where are these changes happening?

Thanks.

**Comment by foragerr** [comment]
There is a link to the commit in my previous comment.

**Comment by g1ps** [comment]
OK, I've located the source of my confusion. You're committing to the JMeter3.0 branch and that's not the default view on the main page.

Thanks again.
