### ISSUE TITLE
Wrong flag referenced in docs. Can't rename results file.

### ISSUE THREAD

**Issue by g1ps** [jmeter-gradle-plugin/jmeter-gradle-plugin#84]
According to the advanced docs,

```
File jmLog                      //maps to -l
  usage: jmLog = file("$buildDir/something.log")
```

jmLog should map to -1 which should allow me to rename the JTL output file.

From http://jmeter.apache.org/usermanual/get-started.html#options Section 2.4.4:

```
-l
    [name of JTL file to log sample results to].
-j
    [name of JMeter run log file].
```

The example in that section makes it clear that it's the JTL file that is renamed.

If I use jmLog, what is written to the renamed file is the run log, usually written to build/jmeter-report/jmeter.log. You probably meant to write -j as the description does reference the log file.

That leaves me without a method of renaming the output files, it seems. Can this be implemented easily as it's something we'd like to do?

Thanks again.

**Comment by foragerr** [comment]
Fixed in dev build [1.0.8-3.0-SNAPSHOT](https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/libs-snapshot/net/foragerr/jmeter/jmeter-gradle-plugin/1.0.8-3.0-SNAPSHOT)

**Comment by g1ps** [comment]
How do I use this? if I change the plugin version to:

```
plugins {
  id "net.foragerr.jmeter" version "1.0.8-3.0-SNAPSHOT"
}
```

I get

```
Plugin [id: 'net.foragerr.jmeter', version: '1.0.8-3.0-SNAPSHOT'] was not found
in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (snapshot plugin versions are not supported)
```

There's no sign of a commit here. The docs haven't changed, either, I assume for the same reason, so I can't see how I should now use these flags. I don't follow.

**Comment by foragerr** [comment]
https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/wiki/Dev-Builds

**Comment by g1ps** [comment]
Thanks. I've added this:

```
buildscript {
    repositories {
        mavenCentral()
        maven {
            url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
        }
    }
    dependencies {
        classpath "net.foragerr.jmeter:jmeter-gradle-plugin:1.0.8-3.0-SNAPSHOT"
    }
}

```

which resulted in this

```
$ gradle run
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Download http://oss.jfrog.org/artifactory/oss-snapshot-local/net/foragerr/jmeter/jmeter-gradle-plugin/1.0.8-3.0-SNAPSHOT/jmeter-gradle-plugin-1.0.8-3.0-20160909.061208-5.pom
Download https://repo1.maven.org/maven2/log4j/log4j/1.2.15/log4j-1.2.15.pom
Download http://oss.jfrog.org/artifactory/oss-snapshot-local/net/foragerr/jmeter/jmeter-gradle-plugin/1.0.8-3.0-SNAPSHOT/jmeter-gradle-plugin-1.0.8-3.0-20160909.061208-5.jar
```

which seems OK, but the build now complains that it can't find jmRun. Any ideas why that would be?

**Comment by foragerr** [comment]
You likely also need to do `apply plugin: 'net.foragerr.jmeter'` editing wiki.

**Comment by foragerr** [comment]
`jmLog` is -j and  
`resultsLog` is -l

**Comment by g1ps** [comment]
> You likely also need to do apply plugin: 'net.foragerr.jmeter' editing wiki.

Thank you, that did it.

> jmLog is -j and
> 
> resultsLog is -l

Brilliant, many thanks.
