### ISSUE TITLE
JSON PostProcessor fails to load

### ISSUE THREAD

**Issue by avamore** [jmeter-gradle-plugin/jmeter-gradle-plugin#89]
I'm trying to use the Gradle plug-in for our jmeter implementation. I am getting the following error:

[gist](https://gist.github.com/avamore/cba006696e107d10f58937cf6d437241)

#57 and #38 mention that the plugin should work out of the box. Before I overcomplicate the project I want to make sure that is still the case.

One thing I notice is that you are loading jMeter 3.0 with jp@gc 1.4 however the latest version is 2.6.

Any guidance?

**Comment by foragerr** [comment]
What version of jmeter did you use to create your jmx test plan?
latest version of what is 2.6?

**Comment by avamore** [comment]
Sorry, versions:

jmeter-gradle-plugin: 1.0.7-3.0-BETA
jmeter used to create jmx plan: 3.0 r1743807

I though I read in the log file that the jp@gc plugin version was set to 1.4, however the latest release is 2.6 for that plugin. I have since learned otherwise.

**Comment by foragerr** [comment]
possible to provide a simplified jmx file that reproduces this issue?

**Comment by avamore** [comment]
[send_to_git.jmx.zip](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/files/720591/send_to_git.jmx.zip)

**Comment by foragerr** [comment]
Can you try with dev build [1.0.8-3.0-SNAPSHOT](https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/libs-snapshot/net/foragerr/jmeter/jmeter-gradle-plugin/1.0.8-3.0-SNAPSHOT)

See here for instructions: https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/wiki/Dev-Builds

**Comment by avamore** [comment]
Yep. Snapshot build seems to work. Thanks!
