### ISSUE TITLE
Enhancement: add option to set report header title

### ISSUE THREAD

**Issue by djangofan** [jmeter-gradle-plugin/jmeter-gradle-plugin#9]
Enhancement: add option to set report header title.   In the 'jmeter-results-report_21.xsl' file that comes with Jmeter, there is a parameter defined like so.   If there is a way to override this with a parameter to the test job, then maybe this could be done?

`<xsl:param name="titleReport" select="'Load Test Results'"/>`

**Comment by foragerr** [comment]
Added new config element:

```
jmeter{
  reportTitle = "custom report title"
}
```
