### ISSUE TITLE
jMeter 3 Support

### ISSUE THREAD

**Issue by g1ps** [jmeter-gradle-plugin/jmeter-gradle-plugin#93]
Hi,

When are we going to see a releases that supports jMeter 3? It seems long overdue. The last commit to the branch was 6 mths ago. We really need this now.

Thanks.

**Comment by foragerr** [comment]
3.3 is now supported

**Comment by g1ps** [comment]
Great, thanks. Where? The branch has gone, there's no release and I'm already using a version later than 1.0.7.

**Comment by g1ps** [comment]
Can someone please advise where this new version resides??!! @foragerr?

**Comment by foragerr** [comment]
@g1ps Please use [v1.0.10-3.3](https://plugins.gradle.org/plugin/net.foragerr.jmeter/1.0.10-3.3)

**Comment by g1ps** [comment]
Thanks. It's finally appeared on the plugin portal.
